id = "charm-mono"
name = "CharmMono Theme"
description = "A beautiful dark theme with purple accents and excellent syntax highlighting."
version = "0.1.0"
schema_version = 1
authors = ["Milos Petrovic <milosptr@hotmail.com>"]
repository = "https://github.com/milosptr/zed-charm-mono-theme"
